### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by silasmahler** [kreinn/kreinn#11]

**Comment by wirebug** [comment]
Habe mal einen Entwurf erstellt. Vielleicht hat @Dekusey ja eine bessere Idee:

![Logo Entwurf](https://i.imgur.com/zHjoKcU.png)

**Comment by silasmahler** [comment]
Das 2te ist nice

**Comment by silasmahler** [comment]
@wirebug Kannst du das die Tage einbinden und vllt noch ein passendes Favicon? Dann ist die HP fast fertig
