### ISSUE TITLE
Teamtexte, Zitate usw einfügen

### ISSUE THREAD

**Issue by jo2** [kreinn/kreinn#14]
- [x] igor
- [x] alex
- [x] christoph
- [x] silas
- [x] johannes
- [x] norbert

**Comment by silasmahler** [comment]
teilweise fertig, zitate fehlen noch
und @iGore @wirebug eure Texte ebenfalls

**Comment by jo2** [comment]
von @fabian-blum und @iGore fehlen noch zitate. bitte im one note oder direkt im html einfügen

**Comment by jo2** [comment]
- Satz von Norbert, Silas, Fabian, Igor
- Erfahrung von Igor
nachpflegen

**Comment by silasmahler** [comment]
@jo2 Bei deinem Zitat fehlt ein Kommata vor "um"
