### ISSUE TITLE
Einheitliche Fotos machen

### ISSUE THREAD

**Issue by jo2** [kreinn/kreinn#25]

**Comment by silasmahler** [comment]
Norbert hat Mittwoch Fototermin @jo2 Kannst dir ja von ihm dann sein Foto senden lassen.
@fabian-blum Hast du noch ein Foto auf dem du etwas mittiger drauf bist in guter Auflösung?

**Comment by silasmahler** [comment]
@fabian-blum Hast du dort nochmal ein Foto oder sollen wir das aktuelle drinlassen?
