### ISSUE TITLE
Impressum erstellen

### ISSUE THREAD

**Issue by jo2** [kreinn/kreinn#30]

**Comment by jo2** [comment]
Hier brauchen wir Informationen von Norbert

**Comment by silasmahler** [comment]
Ja da hast du recht, ich kann leider Dienstag nicht, da sich bei mir ein Meeting auf der Arbeit dazwischen geschoben hat,  deshalb wäre es gut, wenn du ihn dann danach fragst.

**Comment by silasmahler** [comment]
@jo2 Haben wir hier nicht die Möglichkeit auf ein generisches Impressum zuzugreifen?
Sowas zB: http://www.impressum-generator.de/ ?

**Comment by silasmahler** [comment]
hab ich gemacht
