### ISSUE TITLE
Bild und Text Dennis

### ISSUE THREAD

**Issue by silasmahler** [kreinn/kreinn#43]

**Comment by jo2** [comment]
Norbert hätte auch gerne nen bild von seinem hund drin. Sollen wir das machen?

**Comment by silasmahler** [comment]
Ist ein bisschen unkonventionell und mal was anderes, ich bin dafür :)

**Comment by jo2** [comment]
gibt es für den hund schon ein bild?

**Comment by silasmahler** [comment]
closed, see #53
