### ISSUE TITLE
Referenzen einfügen

### ISSUE THREAD

**Issue by silasmahler** [kreinn/kreinn#44]
- [x] Wolf-im-Blut

- [ ] UB-Burzlaff

- [x] Elektro-Günther

**Comment by jo2** [comment]
gibt es das ub-burzlaff-logo mit schwarzer schrift? oder soll ich den hintergrund in grau machen damit man die weiße schrift sieht?

**Comment by silasmahler** [comment]
@jo2 Glaub nicht, Farbe ist auch ok, schrift kann angepasst werden

**Comment by silasmahler** [comment]
Wird zu Release 1.1 verschoben
