### ISSUE TITLE
Add a logo background?

### ISSUE THREAD

**Issue by silasmahler** [kreinn/kreinn#65]
The logo is not very clear to see, maybe a background would help.
Alternatively the Navbar could be white all the time (like when scrolling down), but then the nice animation goes missing, else the logo could be inverted maybe...
![image](https://user-images.githubusercontent.com/14834495/41965529-0c560172-79fd-11e8-8389-dca78f656708.png)

**Comment by jo2** [comment]
![image](https://user-images.githubusercontent.com/7516893/41969627-61ccad80-7a08-11e8-9098-4fba5883c42d.png)
So sähe das invertiert (mit css) aus.
![image](https://user-images.githubusercontent.com/7516893/41969703-995e7b16-7a08-11e8-857d-d0c12233176f.png)
das wäre mit weißem hintergrund.
ist alles grob im browser gemacht aber ich denke die invertierung ist deutlich besser.
allerdings ist das logo etwas klein

**Comment by jo2** [comment]
alternativ andere stockfotos?
